# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  - dotnet restore

build_script:
  - dotnet build .\issuu.sln -c %CONFIGURATION%

test_script:
  - dotnet test .\src\issuu.Tests\

after_build:
  - dotnet pack "src\issuu.Client" -c %CONFIGURATION% /p:Version=%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: '**\*.nupkg'
    name: NuGetPackage

environment:
  IssuuApiCredentials:
    secure: YKsQ0yBp4H0GwZAHsyloOUWcWTA8SKC6akVQA5pqkvNOcFHB1HtYTYcQufs7RIFtVc+R45SzbeN8dFxxV8gSkZgZbEokPvDXajIkxFdTPpO2gUkJbPDPSXEI+iCUXYrE245OiEynhvQgmvdkXC1LPqAbi8gzCeXdO2bsU7SS4Kc=

deploy:
  provider: NuGet
  api_key:
    secure: MICpkYpXVWKu1nitCvEtgAxATawJMxSLboz3RUvOj2XAfdF+IkXuGUG6navDI2dH
  skip_symbols: false
  artifact: '**\*.nupkg'